version: '3'
networks:
  restro-network:
    name: Restro
    driver: bridge
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: restro
    networks:
      - restro-network
    volumes:
      - ./:/app
    expose:
      - 8080
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=api.settings
      - DEBUG=False
      - SECRET_KEY=b41650f9-2139-4824-863c-c252cf0ead5a
      - DB_NAME=restro
      - DB_USER=restro
      - DB_PASSWORD=password
      - DB_HOST=restro.aarsheth.com
      - DB_PORT=5432

  nginx:
    image: nginx
    hostname: nginx
    networks:
      - restro-network
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/django.conf
    depends_on:
      restro:
        condition: service_started
