apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: your-backend-image:latest   # <-- you need to build and push this
        ports:
        - containerPort: 8080
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: DJANGO_SETTINGS_MODULE
          value: "api.settings"
        - name: DEBUG
          value: "False"
        - name: SECRET_KEY
          value: "b41650f9-2139-4824-863c-c252cf0ead5a"
        - name: DB_NAME
          value: "restro"
        - name: DB_USER
          value: "restro"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_HOST
          value: "restro.aarsheth.com"
        - name: DB_PORT
          value: "5432"
