apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  django.conf: |
    # Your nginx.conf content goes here
    server {
      listen 80;
      server_name localhost;

      location / {
          proxy_pass http://backend:8080;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
